BPE: 0
batchSize: 33
beamWidth: 6
dataSet_Sentence: 10000
dataSet_probability: 0.14147610277296632
dataSet_repetition: 5
decoderLayer: 6
embedding_dim: 938
encoderLayer: 2
fixedNumberOfInputElements: 175
hidden_dim: 938
kernel_width: 3
learning_rate: 0.2996954154519163
maximumlearningRateLimit: 0.0001
nestorovsMomentum: 0.99
p_dropout: 0.3487884416974068
patience: 1
renormalizationLimit: 0.1
validationSet: 0.01
