fixedNumberOfInputElements: 175
embedding_dim: 512
hidden_dim: 512
kernel_width: 3
validationSet: 0.01
p_dropout: 0.1
nestorovsMomentum: 0.99
renormalizationLimit: 0.1
learning_rate: 0.25
maximumlearningRateLimit: 0.0001
beamWidth: 5
encoderLayer: 10
decoderLayer: 10
dataSet_Sentence: 1000
dataSet_repetition: 10
dataSet_probability: 0.1

