fixedNumberOfInputElements: 175
embedding_dim: 2
hidden_dim: 2
kernel_width: 3
validationSet: 0.01
p_dropout: 0.1
nestorovsMomentum: 0.99
renormalizationLimit: 0.1
learning_rate: 0.25
maximumlearningRateLimit: 0.0001
beamWidth: 5
encoderLayer: 2
decoderLayer: 2
dataSet_Sentence: 1000
dataSet_repetition: 5
dataSet_probability: 0.08
batchSize: 64
patience: 1
BPE: 0


