BPE: 1
batchSize: 37
beamWidth: 5
dataSet_Sentence: 1000
dataSet_probability: 0.14399281515235848
dataSet_repetition: 3
decoderLayer: 8
embedding_dim: 785
encoderLayer: 5
fixedNumberOfInputElements: 175
hidden_dim: 785
kernel_width: 3
learning_rate: 0.2623598796121799
maximumlearningRateLimit: 0.0001
nestorovsMomentum: 0.99
p_dropout: 0.3951894463325242
patience: 1
renormalizationLimit: 0.1
validationSet: 0.01
