BPE: 0
batchSize: 128
beamWidth: 6
dataSet_Sentence: 50000
dataSet_probability: 0.18
dataSet_repetition: 5
decoderLayer: 15
embedding_dim: 1028
encoderLayer: 15
fixedNumberOfInputElements: 175
hidden_dim: 1028
kernel_width: 3
learning_rate: 0.3
maximumlearningRateLimit: 0.0001
nestorovsMomentum: 0.99
p_dropout: 0.4
patience: 1
renormalizationLimit: 0.1
validationSet: 0.01
