BPE: 1
batchSize: 47
beamWidth: 5
dataSet_Sentence: 20000
dataSet_probability: 0.1470863195582148
dataSet_repetition: 4
decoderLayer: 12
embedding_dim: 946
encoderLayer: 4
fixedNumberOfInputElements: 175
hidden_dim: 946
kernel_width: 3
learning_rate: 0.315762073010458
maximumlearningRateLimit: 0.0001
nestorovsMomentum: 0.99
p_dropout: 0.35777172546302377
patience: 2
renormalizationLimit: 0.1
validationSet: 0.01
