BPE: 0
batchSize: 35
beamWidth: 5
dataSet_Sentence: 10000
dataSet_probability: 0.17257354238497014
dataSet_repetition: 3
decoderLayer: 7
embedding_dim: 795
encoderLayer: 5
fixedNumberOfInputElements: 175
hidden_dim: 795
kernel_width: 3
learning_rate: 0.2823487178314487
maximumlearningRateLimit: 0.0001
nestorovsMomentum: 0.99
p_dropout: 0.3004092745268902
patience: 1
renormalizationLimit: 0.1
validationSet: 0.01
