fixedNumberOfInputElements: 175
embedding_dim: 256
hidden_dim: 256
kernel_width: 3
validationSet: 0.01
p_dropout: 0.1
nestorovsMomentum: 0.99
renormalizationLimit: 0.1
learning_rate: 0.25
maximumlearningRateLimit: 0.0001
beamWidth: 5
encoderLayer: 15
decoderLayer: 15
dataSet_Sentence: 100000
dataSet_repetition: 5
dataSet_probability: 0.1
batchSize: 64
patience: 1

